{% set version = "1.0.0" %}

package:
  name: sloshl
  version: {{ version }}

build:
  number: 0
  noarch: true

requirements:
  build: 
    - make
    - git

test:
  requires: 
    - qunit
  files:
    - test/
  source_files:
    - src/
