package:
  name: backslashl
  version: {{ environ.get('GIT_DESCRIBE_TAG', '0.0.1') }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script: cp -r ${SRC_DIR}/* ${PREFIX}/

requirements:
  build:
    - kdb

source:
  path: ../../
