package:
  name: backslashl
  version: {{ environ.get('GIT_DESCRIBE_TAG', '0.0.1') }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script: make build Q_BUILD_PATH="/Users/doolzer/work/pkg"

requirements:
  build:
    - kdb

source:
  path: ../../
