package:
  name: backslashl
  version: {{ RELEASE_TAG }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script_env:
    - RELEASE_TAG
  script: cp -r ${SRC_DIR}/* ${PREFIX}

requirements:
  - kdb==4.0

source:
  path: ../..
